//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHAKHOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public long ID { get; set; }
        public Nullable<long> IDTooth { get; set; }
        public string Color { get; set; }
        public string Prod { get; set; }
        public Nullable<System.DateTime> Recevicedate { get; set; }
        public Nullable<System.DateTime> Senddate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Category { get; set; }
        public Nullable<long> IDBill { get; set; }
        public Nullable<int> Count { get; set; }
        public string ToothNumber { get; set; }
    }
}
