//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHAKHOA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Bill
    {
        public long ID { get; set; }
        [DisplayName("Khách hàng")]
        public Nullable<long> IDCustomer { get; set; }

        [DisplayName("Phòng khám")]
        public Nullable<long> IDDentalClinic { get; set; }

        [DisplayName("Bác sĩ")]
        public string Doctor { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<int> Status { get; set; }
        [DisplayName("Mã phiếu khám")]
        public string Code { get; set; }
        [DisplayName("Mã bảo hành")]
        public string CodeBH { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        public string Createby { get; set; }
        public string Editby { get; set; }

        [DisplayName("Ngày nhận")]
        public Nullable<System.DateTime> Recevicedate { get; set; }
        [DisplayName("Ngày giao")]
        public Nullable<System.DateTime> Senddate { get; set; }
        [DisplayName("Phân loại")]
        public string Category { get; set; }
        [DisplayName("Loại sứ")]
        public string CateTooth { get; set; }
        public Nullable<int> CountBH { get; set; }

    }
}
