//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHAKHOA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public long ID { get; set; }
        [DisplayName("Họ và tên")]
        [Required]
        public string Name { get; set; }
        [DisplayName("Số điện thoại")]
        [Required]
        public string PhoneNumber { get; set; }
        [DisplayName("Địa chỉ")]
        public string Adress { get; set; }
        [DisplayName("Phường")]
        public string Ward { get; set; }
        [DisplayName("Quận")]
        public string District { get; set; }
        [DisplayName("Thành phố")]
        public string Province { get; set; }
        
        public Nullable<int> SumWarranti { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        [DisplayName("Ngày sinh")]
        [Required]
        public Nullable<System.DateTime> Birthday { get; set; }
        [DisplayName("Giới tính")]
        [Required]
        public Nullable<int> Sex { get; set; }
        public string Createby { get; set; }
        public string Editby { get; set; }
    }
}
