//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHAKHOA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DentalClinic
    {
        public long ID { get; set; }
        [DisplayName("Phòng khám")]
        public string Name { get; set; }
        [DisplayName("Địa chỉ")]
        public string Adress { get; set; }
        [DisplayName("Phường")]
        public string Ward { get; set; }
        [DisplayName("Quận")]
        public string District { get; set; }
        [DisplayName("Thành phố")]
        public string Province { get; set; }
        [DisplayName("Số điện thoại")]
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        [DisplayName("Ghi chú")]
        public string Note { get; set; }
    }
}
