//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHAKHOA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tooth
    {
        public long ID { get; set; }
        [DisplayName("Loại răng")]
        public string Name { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        [DisplayName("Hạn bảo hành")]
        public int Limited { get; set; }
        [DisplayName("Mã sứ")]
        public string Code { get; set; }
    }
}
