//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHAKHOA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Warranti
    {
        public long ID { get; set; }
        public Nullable<long> ID_Bill { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        [DisplayName("Công việc")]
        public string Note { get; set; }
        [DisplayName("Phòng khám")]
        public Nullable<long> ID_Dental { get; set; }
        [DisplayName("Bác sĩ")]
        public string Doctor { get; set; }
        [DisplayName("Ngày hoàn thành")]
        public Nullable<System.DateTime> Successdate { get; set; }
        [DisplayName("Ngày giao")]
        public Nullable<System.DateTime> Senddate { get; set; }
    }
}
